name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{env.secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{env.secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build docker image
      run: docker build . --file Dockerfile --tag hmahara/halo-dunia:latest
    - name: docker push
      run: docker push ${{env.secrets.DOCKER_USER}}/halo-dunia
